### ISSUE TITLE
pod install error

### ISSUE THREAD

**Issue by taitanxiami** [isaced/fir-mac#1]
error message:
Unable to find a target named `fir-mac`, did find `fir.im`.

**Comment by taitanxiami** [comment]
Podfile 中的target 应该是fir.im

**Comment by isaced** [comment]
是的，之前改项目名忘了改 Podfile 里的 scheme name，现在已经改过来了。

**Comment by taitanxiami** [comment]
我这边还是一直跑不起来。

Apple Mach -O Linker(Id)Error
Linker command failed with exit code 1(use -v to invocation)

**Comment by isaced** [comment]
现在 pull 试试，应该是之前改 target name 给搞乱了

**Comment by taitanxiami** [comment]
可以了。
