### ISSUE TITLE
添加 scheme

### ISSUE THREAD

**Issue by sablib** [isaced/fir-mac#3]
支持`open ${scheme}://upload?path=${path}`这样的方式来进行上传。

**Comment by isaced** [comment]
是想在其他地方唤起 fir-mac 进行上传动作吗？

**Comment by sablib** [comment]
对，比如可以在命令行打开上传。
也是刚才发现 fastlane 的 fir 插件有问题才想起来的。

**Comment by isaced** [comment]
好想法，一会来添加这个。

**Comment by isaced** [comment]
已添加通过 URL scheme 唤起上传功能

```
fir-mac://upload?filepath=path/to/xx.ipa
```
